version: "3"

services:

  pywb-warcprox:
    image: webrecorder/pywb:2.6.8
    command: /start-pywb.sh
    ports:
      - "8080:8080"
    volumes:
      - ./pywb-warcprox:/webarchive/collections
      - ./pywb-config.yml:/webarchive/config.yaml
      - ./start-pywb.sh:/start-pywb.sh

  warcprox:
    image: ukwa/docker-warcprox:2.4.17.2
    #command: "warcprox -b 0.0.0.0 -d /heritrix/wren --base32 --gzip --rollover-idle-time 600 --dedup-db-file /dev/null --stats-db-file /dev/null --quiet --plugin warcprox-plugins.listeners.KafkaCaptureFeed --plugin warcprox-plugins.listeners.UpdateOutbackCDX"
    #command: "warcprox -b 0.0.0.0 -d /output --base32 --gzip --rollover-idle-time 600 --dedup-db-file /dev/null --stats-db-file /dev/null --quiet --plugin warcprox-plugins.listeners.UpdateOutbackCDX"
    command: "warcprox -b 0.0.0.0 -d /output --base32 --gzip --rollover-idle-time 600 --dedup-db-file /dev/null --stats-db-file /dev/null --quiet"
    environment:
      - "LC_ALL=en_US.utf8"
      - "TMP=/tmp/warcprox"
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
      - "KAFKA_CRAWLED_TOPIC=fc.crawled"
      - "KAFKA_CRAWLED_ACKS=1"
      - "CDXSERVER_ENDPOINT=http://cdxserver:8080/fc"
    ports:
      - "8000:8000"
    ulimits:
      nproc: 2000 # See https://github.com/internetarchive/warcprox/blob/2.x/warcprox/warcproxy.py#L413
    volumes:
      - ./warcprox:/output

  # tinycdxserver
  cdxserver:
    image: nlagovau/outbackcdx:0.7.0
    # Verbose form logs submissions:
    #command: "java -jar outbackcdx.jar -v -d /cdx-data -p 8080 -b 0.0.0.0"
    ports:
      - "9090:8080"
    volumes:
      - cdx-data:/cdx-data

  # URL Frontier
  urlfrontier:
    user: root
    image: crawlercommons/url-frontier:2.3.1
    command: -s 9100 rocksdb.path=/storage/rocksdb
    ports:
    - "7071:7071"
    - "9100:9100"   
    volumes:
      - urlfrontier-storage:/storage

volumes:
  urlfrontier-storage:
  cdx-data:

